src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Runtime;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Screening", mappedBy="movie")
     */
    private $Screening;

    public function __construct()
    {
        $this->Screening = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getRuntime(): ?int
    {
        return $this->Runtime;
    }

    public function setRuntime(int $Runtime): self
    {
        $this->Runtime = $Runtime;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    public function __toString(){
        return $this->getTitle();
    }

    /**
     * @return Collection|Screening[]
     */
    public function getScreening(): Collection
    {
        return $this->Screening;
    }

    public function addScreening(Screening $screening): self
    {
        if (!$this->Screening->contains($screening)) {
            $this->Screening[] = $screening;
            $screening->setMovie($this);
        }

        return $this;
    }

    public function removeScreening(Screening $screening): self
    {
        if ($this->Screening->contains($screening)) {
            $this->Screening->removeElement($screening);
            // set the owning side to null (unless already changed)
            if ($screening->getMovie() === $this) {
                $screening->setMovie(null);
            }
        }

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Entity\Screening;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MovieController extends AbstractController
{
    /**
     * @Route("/allmovies", name="allMovies")
     */
    public function index(Request $request)
    {
        $repository = $this->getDoctrine()->getRepository(Movie::class);
        $movies = $repository->findAll();
        $form = $this->createFormBuilder()
            ->add('name', TextType::class, [
                'attr' => ['class' => 'tinymce'],
            ])
            ->add('save', SubmitType::class, ['label' => 'Search'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $form->getData();
            return $this->redirectToRoute('allMoviesFilter', ["movies" => $form->getData()]);
        }
        return $this->render('movie/allMovies.twig', [
            'movies' => $movies, 'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/singleMovie/{id}", name="singleMovie")
     */
    public function singleMovie($id){
        $repository = $this->getDoctrine()->getRepository(Movie::class);
        $movie = $repository->find($id);
        $getScreenings = $this->getDoctrine()->getRepository(Screening::class)->findAll();
        $allScreenings = [];
        foreach ($getScreenings as $value){
            if($value->getMovie()->getId() == $id){
                array_push($allScreenings, $value);
            }
        }

        return $this->render('movie/singleMovie.html.twig', ["movie" => $movie, 'screenings' => $allScreenings]);
    }
    /**
     * @Route("/allmovies/filter", name="allMoviesFilter")
     */
    public function filterMovies(Request $request)
    {
        $filterName = $request->query->get('movies');
        $repository = $this->getDoctrine()->getRepository(Movie::class);
        $movies = $repository->findAll();

        $form = $this->createFormBuilder()
            ->add('name', TextType::class, [
                'attr' => ['class' => 'tinymce'],
            ])
            ->add('save', SubmitType::class, ['label' => 'Search'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $form->getData();
            return $this->redirectToRoute('allMoviesFilter', ["movies" => $form->getData()]);
        }

        $moviesFilter = [];

        foreach ($movies as $value){
            if (strpos(strtoupper($value->getTitle()), strtoupper(reset($filterName))) !== false) {
                array_push($moviesFilter, $value);
            }
        }

        return $this->render('movie/allMovies.twig', [
            'movies' => $moviesFilter, 'form' => $form->createView()
        ]);
    }
}

templates/movie/allMovies.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MovieController!{% endblock %}

{% block body %}
        <style>
                .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
                .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        </style>
    {{ form(form) }}
        <div class="allmovies">
                {% for movie in movies %}
                        <li>
                                <h3>{{ movie.title }}</h3>
                                <p class="description">{{ movie.description }}</p>
                                <p class="time">{{ movie.runtime }} minutes</p>
                                <a href="{{ path("singleMovie", {"id": movie.id}) }}">See more</a>
                        </li>
                {% endfor %}
        </div>
    <a href="{{ path('allMovies') }}">See all movies</a>

{% endblock %}

templates/movie/singleMovie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MovieController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="allmovies">
            <li>
                <h3>{{ movie.title }}</h3>
                <p class="description">{{ movie.description }}</p>
                <p class="time">{{ movie.runtime }} minutes</p>
                {% for screening in screenings %}
                    {{ screening.date|date('Y-m-d') }}
                    {{ screening.room }}
                    <a href="{{ path('reservationConfirm', {"id": screening.id}) }}">Book this screening</a>
                {% endfor %}
            </li>

    </div>
    <a href="{{ path('allMovies') }}">See all movies</a>
{% endblock %}