src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Capacity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->Capacity;
    }

    public function setCapacity(int $Capacity): self
    {
        $this->Capacity = $Capacity;

        return $this;
    }
    public function __toString(){
        return $this->getName();
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class DashboardController extends AbstractController
{
    /**
     * @Route("/dashboard", name="dashboard")
     */
    public function index()
    {
        $reservations = $this->getDoctrine()->getRepository(Reservation::class)->findAll();
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $allUserReservations =[];
        foreach ($reservations as $value) {
            if($value->getUser()->getId() == $user->getId())
                array_push($allUserReservations, $value);
        }

        return $this->render('dashboard/index.html.twig', [
            'userReservations' => $allUserReservations,
        ]);
    }
    /**
     * @Route("/deletereservation/{id}", name="deleteReservation")
     * @ParamConverter("id", class=Reservation::class)
     */
    public function deleteReservation($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $reservation = $this->getDoctrine()->getRepository(Reservation::class)->find($id);
        $entityManager->remove($reservation);
        $entityManager->flush();

        return $this->redirectToRoute('dashboard');
    }
    /**
     * @Route("/modifyreservation/{id}", name="modifyReservation")
     */
    public function modifyReservation($id)
    {
        $reservations = $this->getDoctrine()->getRepository(Reservation::class)->findAll();
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $allUserReservations =[];
        foreach ($reservations as &$value) {
            if($value->getUser()->getId() == $user->getId())
                array_push($allUserReservations, $value);
        }

        return $this->render('dashboard/modifyReservation.html.twig', [
            'userReservations' => $allUserReservations,
        ]);
    }
}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DashboardController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{% for reservation in userReservations %}
    {{ reservation.screening.movietitle }}
    {{ reservation.screening.date|date("Y-m-d") }}
    {{ reservation.capacity }}
    <a href="{{ path("modifyReservation", {"id": reservation.id}) }}">Modify</a>
    <a href="{{ path("deleteReservation", {"id": reservation.id}) }}">Delete</a>
{% endfor %}
{% endblock %}

templates/dashboard/modifyReservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DashboardController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    {% for reservation in userReservations %}
        {{ reservation.seance.movietitle }}
        {{ reservation.seance.date|date("Y-m-d") }}
        {{ reservation.capacity }}
        <a href="{{ path("modifyReservation", {"id": reservation.id}) }}">Modify</a>
        <a href="{{ path("deleteReservation", {"id": reservation.id}) }}">Delete</a>
    {% endfor %}
{% endblock %}